### PR TITLE
Added getting started example with Open Telemetry for Golang

### PR DESCRIPTION
**Pull request by utr1903**

### CODE REVIEW

**Comment by reese-lee** [comment]
This PR is to add a Get Started with OTel Go tutorial to our examples repo, similar to what we have for [Java](https://github.com/newrelic/newrelic-opentelemetry-examples/tree/main/getting-started-guides/java).

Hey @utr1903, thank you so much for putting together a Golang example for our Get Started Guides for OTel! I have a few notes for you:

1. I see that the directories have already been broken out into `Instrumented` and `Uninstrumented`; could you put the load generators into each of those directories, instead of in their own? We want the examples to be as similar to each other as possible. 

2. We'd like all the examples to use the same port; could you update the app to use port 8080? 

3. It looks like the README contains a lot of what we'd want to use in the actual documentation for the guide; it contains a lot of great info, but for a repo README we'll want to abbreviate it. Is the README what you'd like to use for the guide in the docs? 

Thanks again!

**Comment by utr1903** [comment]
Hi @reese-lee!

1. I can put the load generators into each folder, sure.
2. I can change also change the port to `8080`.
3. If I would be anyone who would like to use the repo, I would prefer not to switch between the repo & docs back and forth. When one opens up the repo in their IDEs, everything they need would be simply there. Would you consider to keep the `README` as it is?

Plus: I will update the code with the current API versions.

**Comment by utr1903** [comment]
@reese-lee Changes are merged (see [PR](https://github.com/utr1903/newrelic-opentelemetry-examples/pull/5))

**Comment by reese-lee** [comment]
@utr1903 Hey Ugur! Thank you so much for your patience. We recently published [a spec guide for the demo applications](https://github.com/newrelic/newrelic-opentelemetry-examples/blob/main/getting-started-guides/demo-app-specification.md), can you review it when you get a chance and confirm that your Go demo app meets the requirements?

**Comment by reese-lee** [comment]
At least for traces, and metrics where applicable; I'm aware that logs is frozen.

**Review by alanwest — APPROVED** [review]
Thanks @utr1903! I have not reviewed super closely, but at quick glance it appears to check most of our boxes. I'm working to reorganize this repo, so I'll merge this as is and will iterate as necessary to meet our needs.

**Pull request merged**
